name: null
favicon: null
layout_spectrum: 0.4206115792039782
typography_spectrum: 0.6016716789454222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.944743133848533
  lightness: 0.8904487325344235
  saturation: 0.5126054789870977
  rhythmicContrast: 0.44152959040366113
purpose: []
